### ISSUE TITLE
Add DuckDuckGo as search engine

### ISSUE THREAD

**Issue by Eagle3386** [mrlacey/ErrorHelper#14]
… or better yet: instead of extending an enum time and time again, maybe switch to a textbox, containing the search provider's URL up to the common `q=` query parameter?

**Comment by mrlacey** [comment]
v2.7 is now in the marketplace and includes DuckDuckGo as an option.
I did this now as a quick/simple improvement.

I'll follow up with a future update to make this configurable.

I didn't do this previously because:
- Very little use of this extension
- Not getting a lot of requests for changes or additional functionality.
- Adding a new search engine option is really quick and easy.
- Configurable entry will require a lot more handling for potential errors.... ;)

**Comment by mrlacey** [comment]
v2.8 will include this: 
![image](https://github.com/mrlacey/ErrorHelper/assets/189547/4cf1b260-8dd6-469a-87b0-69bed6ce2fb0)

**Comment by Eagle3386** [comment]
Unbelievable! It's _exactly_ how I imagined it.
Just pure awesomeness - right there.
Thanks so much! ❤️

**Comment by mrlacey** [comment]
Originally I thought it was going to be more complicated. Glad I didn't rush into it with my original plan and glad this works as you wanted.

**Comment by Eagle3386** [comment]
It's so good, I even sponsored you just because of this. Again, thanks a lot, Matt! 👏🏻👍🏻
